/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DissectionDump: typeof import('./src/components/DissectionDump.vue')['default']
    DissectionTree: typeof import('./src/components/DissectionTree.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HighlightedText: typeof import('./src/components/HighlightedText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
