name: Build & Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    if: |
      !contains(github.event.head_commit.message, 'skip-ci')

    steps:
    - uses: actions/checkout@v3
    
    - name: Stash old path
      run: echo "OLD_PATH=$PATH" >> "${GITHUB_ENV}"

    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v11
      with:
        version: 3.1.31
        # actions-cache-folder: 'emsdk-cache'

    - name: Verify EMSDK
      run: emcc -v

    - name: Install build tools
      run: |
        sudo apt-get -qq -y update && sudo DEBIAN_FRONTEND="noninteractive" TZ="America/San_Francisco" apt-get install -y --no-install-recommends \
          flex \
          lemon \
          pkg-config \
          cmake \
          ninja-build \
          meson \
          autoconf \
          automake \
          autopoint \
          libtool \
          libltdl-dev

    - uses: actions/cache@v3
      with:
        path: |
          built/*
          !built/bin/wiregasm.js
          !built/bin/wiregasm.wasm
          !built/share/wiregasm/wiregasm.data
          lib/*
          !lib/wiregasm
          !lib/crossfile.meson
          !lib/Makefile
        key: lib-${{ hashFiles('patches/**', 'lib/Makefile', 'lib/crossfile.meson') }}

    - name: Build WASM lib
      run: npm run build:emscripten-local

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lib
        path: |
          built/bin/wiregasm.*

    # hack to not use node 14 bundled with emsdk
    - name: Restore Path
      run: echo "$OLD_PATH" > $GITHUB_PATH

    - name: Load Dependencies
      run: npm ci

    - name: Run Tests
      run: npm test
